version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    entrypoint: ["/usr/src/app/entrypoint.sh"]
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@postgre:5432/users_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@postgre:5432/users_test
    depends_on:
      - postgre
      - elasticsearch

  postgre:
    build:
      context: ./app/db
      dockerfile: db.Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
