name: "Pipeline for python applications"

on: [push]

jobs:
  lint:
    name: "Lints the code using psf/black"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      
      - name: Install black
        run: |
          python -m pip install --upgrade pip setuptools black
          black --config pyproject.toml .
